// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	recovery "github.com/RagOfJoes/mylo/flow/recovery"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, newFlow
func (_m *Repository) Create(ctx context.Context, newFlow recovery.Flow) (*recovery.Flow, error) {
	ret := _m.Called(ctx, newFlow)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, recovery.Flow) *recovery.Flow); ok {
		r0 = rf(ctx, newFlow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, recovery.Flow) error); ok {
		r1 = rf(ctx, newFlow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *Repository) Get(ctx context.Context, id uuid.UUID) (*recovery.Flow, error) {
	ret := _m.Called(ctx, id)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *recovery.Flow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFlowIDOrRecoverID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByFlowIDOrRecoverID(ctx context.Context, id string) (*recovery.Flow, error) {
	ret := _m.Called(ctx, id)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, string) *recovery.Flow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdentityID provides a mock function with given fields: ctx, identityID
func (_m *Repository) GetByIdentityID(ctx context.Context, identityID uuid.UUID) (*recovery.Flow, error) {
	ret := _m.Called(ctx, identityID)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *recovery.Flow); ok {
		r0 = rf(ctx, identityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, identityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, updateFlow
func (_m *Repository) Update(ctx context.Context, updateFlow recovery.Flow) (*recovery.Flow, error) {
	ret := _m.Called(ctx, updateFlow)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, recovery.Flow) *recovery.Flow); ok {
		r0 = rf(ctx, updateFlow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, recovery.Flow) error); ok {
		r1 = rf(ctx, updateFlow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
