// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	recovery "github.com/RagOfJoes/mylo/flow/recovery"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, id
func (_m *Service) Find(ctx context.Context, id string) (*recovery.Flow, error) {
	ret := _m.Called(ctx, id)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, string) *recovery.Flow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// New provides a mock function with given fields: ctx, requestURL
func (_m *Service) New(ctx context.Context, requestURL string) (*recovery.Flow, error) {
	ret := _m.Called(ctx, requestURL)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, string) *recovery.Flow); ok {
		r0 = rf(ctx, requestURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitIdentifier provides a mock function with given fields: ctx, flow, payload
func (_m *Service) SubmitIdentifier(ctx context.Context, flow recovery.Flow, payload recovery.IdentifierPayload) (*recovery.Flow, error) {
	ret := _m.Called(ctx, flow, payload)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, recovery.Flow, recovery.IdentifierPayload) *recovery.Flow); ok {
		r0 = rf(ctx, flow, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, recovery.Flow, recovery.IdentifierPayload) error); ok {
		r1 = rf(ctx, flow, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitUpdatePassword provides a mock function with given fields: ctx, flow, payload
func (_m *Service) SubmitUpdatePassword(ctx context.Context, flow recovery.Flow, payload recovery.SubmitPayload) (*recovery.Flow, error) {
	ret := _m.Called(ctx, flow, payload)

	var r0 *recovery.Flow
	if rf, ok := ret.Get(0).(func(context.Context, recovery.Flow, recovery.SubmitPayload) *recovery.Flow); ok {
		r0 = rf(ctx, flow, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Flow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, recovery.Flow, recovery.SubmitPayload) error); ok {
		r1 = rf(ctx, flow, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
