// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	identity "github.com/RagOfJoes/mylo/user/identity"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// SendRecovery provides a mock function with given fields: to, recoveryURL
func (_m *Client) SendRecovery(to []string, recoveryURL string) error {
	ret := _m.Called(to, recoveryURL)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, string) error); ok {
		r0 = rf(to, recoveryURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendVerification provides a mock function with given fields: to, user, verificationURL
func (_m *Client) SendVerification(to string, user identity.Identity, verificationURL string) error {
	ret := _m.Called(to, user, verificationURL)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, identity.Identity, string) error); ok {
		r0 = rf(to, user, verificationURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWelcome provides a mock function with given fields: to, user, verificationURL
func (_m *Client) SendWelcome(to string, user identity.Identity, verificationURL string) error {
	ret := _m.Called(to, user, verificationURL)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, identity.Identity, string) error); ok {
		r0 = rf(to, user, verificationURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
