version: "3.8"
services:
  db:
    container_name: "idp-dev-db"
    build:
      context: ./docker/
      dockerfile: Dockerfile.pg
    env_file:
      - pg.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  dev:
    working_dir: /idp
    container_name: "idp-dev"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/idp
    depends_on:
      - db
volumes:
  pgdata:
