// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Attributes is an autogenerated mock type for the Attributes type
type Attributes struct {
	mock.Mock
}

// GetValue provides a mock function with given fields:
func (_m *Attributes) GetValue() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *Attributes) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *Attributes) Reset() {
	_m.Called()
}

// SetValue provides a mock function with given fields: value
func (_m *Attributes) SetValue(value interface{}) {
	_m.Called(value)
}
