# See https://github.com/chemidy/smallest-secured-golang-docker-image/blob/master/docker/scratch.Dockerfile

############################
# STEP 1 build executable binary
############################
FROM golang:alpine as builder

# Install git + SSL ca certificates.
# Git is required for fetching the dependencies.
# Ca-certificates is required to call HTTPS endpoints.
RUN apk update && apk add --no-cache git ca-certificates tzdata && update-ca-certificates

# Create raggy
ENV USER=raggy
ENV UID=10001

# See https://stackoverflow.com/a/55757473/12429735
RUN adduser \
	--disabled-password \
	--gecos "" \
	--home "/nonexistent" \
	--shell "/sbin/nologin" \
	--no-create-home \
	--uid "${UID}" \
	"${USER}"
WORKDIR $GOPATH/src/github.com/RagOfJoes/ragofjoes-idp/

# Copy go modules then download and verify
COPY go.mod .
RUN go mod download
RUN go mod verify

COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
	-ldflags='-w -s -extldflags "-static"' -a \
	-o /go/bin/ragofjoes-idp cmd/idp/main.go

############################
# STEP 2 build a small image
############################
FROM scratch

# Import from builder.
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

# Copy our static executable
COPY --from=builder /go/bin/ragofjoes-idp /go/bin/ragofjoes-idp

# Use an unprivileged user.
USER raggy:raggy

# Expose volume so that users can mount their configuration file
VOLUME /home/raggy

# Run the binary.
ENTRYPOINT ["/go/bin/lumpia"]
